"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": ".."

"preserve_hierarchy": true

"files": [
  {
    "source": "output/nvda.pot",
    "translation": "source/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "user_docs/en/changes.xliff",
    "translation": "user_docs/%two_letters_code%/changes.xliff"
  },
  {
    "source": "user_docs/en/userGuide.xliff",
    "translation": "user_docs/%two_letters_code%/userGuide.xliff"
  }
]
